# Generated by Django 3.2.25 on 2024-03-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(blank=True, max_length=100, null=True)),
                ('entryClientId', models.CharField(blank=True, max_length=100, null=True)),
                ('entryOrderId', models.CharField(blank=True, max_length=100, null=True)),
                ('entryQuant', models.IntegerField(blank=True, null=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('targetClientIdBase', models.CharField(blank=True, max_length=100, null=True)),
                ('targetOrderIdBase', models.CharField(blank=True, max_length=100, null=True)),
                ('stop', models.CharField(blank=True, max_length=100, null=True)),
                ('activateNewEntry', models.BooleanField(blank=True, default=False, null=True)),
                ('newEntry', models.CharField(blank=True, max_length=100, null=True)),
                ('newEntryQuant', models.IntegerField(blank=True, null=True)),
                ('newTarget', models.CharField(blank=True, max_length=100, null=True)),
                ('clientOrderId', models.CharField(blank=True, max_length=100, null=True)),
                ('orderId', models.CharField(blank=True, max_length=100, null=True)),
                ('targetClientId', models.CharField(blank=True, max_length=100, null=True)),
                ('targetOrderId', models.CharField(blank=True, max_length=100, null=True)),
                ('activateNewEntry2', models.BooleanField(blank=True, default=False, null=True)),
                ('newEntry2', models.CharField(blank=True, max_length=100, null=True)),
                ('newEntryQuant2', models.IntegerField(blank=True, null=True)),
                ('newTarget2', models.CharField(blank=True, max_length=100, null=True)),
                ('clientOrderId2', models.CharField(blank=True, max_length=100, null=True)),
                ('orderId2', models.CharField(blank=True, max_length=100, null=True)),
                ('targetClientId2', models.CharField(blank=True, max_length=100, null=True)),
                ('targetOrderId2', models.CharField(blank=True, max_length=100, null=True)),
                ('activateNewEntry3', models.BooleanField(blank=True, default=False, null=True)),
                ('newEntry3', models.CharField(blank=True, max_length=100, null=True)),
                ('newEntryQuant3', models.IntegerField(blank=True, null=True)),
                ('newTarget3', models.CharField(blank=True, max_length=100, null=True)),
                ('clientOrderId3', models.CharField(blank=True, max_length=100, null=True)),
                ('orderId3', models.CharField(blank=True, max_length=100, null=True)),
                ('targetClientId3', models.CharField(blank=True, max_length=100, null=True)),
                ('targetOrderId3', models.CharField(blank=True, max_length=100, null=True)),
                ('activateNewEntry4', models.BooleanField(blank=True, default=False, null=True)),
                ('newEntry4', models.CharField(blank=True, max_length=100, null=True)),
                ('newEntryQuant4', models.IntegerField(blank=True, null=True)),
                ('newTarget4', models.CharField(blank=True, max_length=100, null=True)),
                ('clientOrderId4', models.CharField(blank=True, max_length=100, null=True)),
                ('orderId4', models.CharField(blank=True, max_length=100, null=True)),
                ('targetClientId4', models.CharField(blank=True, max_length=100, null=True)),
                ('targetOrderId4', models.CharField(blank=True, max_length=100, null=True)),
                ('baseLeverage', models.IntegerField(blank=True, default=1, null=True)),
                ('currentLeverage', models.IntegerField(blank=True, default=1, null=True)),
                ('newStart', models.BooleanField(blank=True, default=True, null=True)),
                ('targetDist', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
