# Generated by Django 3.2.24 on 2024-02-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='baseLeverage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
