# Generated by Django 3.2.24 on 2024-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_entries_baseleverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='baseLeverage',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
