# Generated by Django 3.2.24 on 2024-02-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_alter_entries_baseleverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='currentLeverage',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
