# Generated by Django 3.2.24 on 2024-02-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_entries_currentleverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='activateNewEntry',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
