# Generated by Django 3.2.24 on 2024-02-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_entries_activatenewentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='newStart',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
