# Generated by Django 3.2.24 on 2024-02-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_entries_newstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='entry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='newEntry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='newTarget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='stop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
