# Generated by Django 3.2.24 on 2024-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0007_auto_20240229_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='newEntry2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='newEntry3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='newEntry4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='newTarget2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='newTarget3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='newTarget4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
