# Generated by Django 3.2.24 on 2024-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0008_auto_20240303_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='activateNewEntry2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='activateNewEntry3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='activateNewEntry4',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
