# Generated by Django 3.2.24 on 2024-03-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0010_auto_20240305_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
