# Generated by Django 3.2.24 on 2024-03-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0012_auto_20240305_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='entryQuant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='newEntryQuant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='newEntryQuant2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='newEntryQuant3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='newEntryQuant4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
