# Generated by Django 3.2.25 on 2024-03-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0013_auto_20240306_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='entryClientId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='entryOrderId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='targetDist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
