# Generated by Django 3.2.25 on 2024-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0014_auto_20240308_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentDay', models.DateField()),
            ],
        ),
    ]
