# Generated by Django 3.2.25 on 2024-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0015_secondbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondbot',
            name='dailyProfit',
            field=models.FloatField(default=0),
        ),
    ]
