# Generated by Django 3.2.25 on 2024-07-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0016_secondbot_dailyprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondbot',
            name='startingDayBalance',
            field=models.FloatField(default=1000),
        ),
    ]
